### ISSUE TITLE
3-3에서 가장 상단 변수에

### ISSUE THREAD

**Issue by Leeyoohyuk** [KHU-Dcom-Study/2018-1-DeepLearning-Study#10]
W = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
라는 코드가 무슨뜻이죠

**Comment by kairos03** [comment]
https://www.tensorflow.org/api_docs/python/tf/random_uniform

**Comment by Leeyoohyuk** [comment]
random_uniform 모든 변수에 대해 같은확률로 변수를 초기화한다는 뜻입니다
[1] 이 행렬의 크기임
