### ISSUE TITLE
name을 붙이는 이유

### ISSUE THREAD

**Issue by Leeyoohyuk** [KHU-Dcom-Study/2018-1-DeepLearning-Study#11]
X = tf.placeholder(tf.float32, name="X")

**Comment by YeongBean** [comment]
변수가 저장될 때 X로 저장이 안된답니다. 그래서 코드 내부 외의 어딘가에 변수를 써야 할 때(텐서보드 ....) X라는걸 알아볼려고 name을 써주는거라네요
