### ISSUE TITLE
git 연습 2장 6번.. 문제가 요구하는게 뭐죠?

### ISSUE THREAD

**Issue by Leeyoohyuk** [KHU-Dcom-Study/2018-1-DeepLearning-Study#18]
![1](https://user-images.githubusercontent.com/37439276/37861436-0012f8cc-2f7d-11e8-980b-7abc8462def2.PNG)

**Comment by JunjaK** [comment]
git commit 96f1625 같이 노란색 글자 commit 바로 뒤의 7자리 문자를 입력하면 됩니다.
