### ISSUE TITLE
git commit 의 용도가 무엇인가요?

### ISSUE THREAD

**Issue by Leeyoohyuk** [KHU-Dcom-Study/2018-1-DeepLearning-Study#19]
특히 git commit -m "Commit message" 문구의 기능을 모르겠습니다~ 연습문제에 자주쓰던데

**Comment by JunjaK** [comment]
우리가 보는 강좌에서는 
git commit -m "name" : permanently stores file changes from the staging area in the repository
이렇게 설명하는데.. 
아래 링크 참조하면 더 이해하기 좋을거 같네여
https://backlog.com/git-tutorial/kr/intro/intro1_3.html

**Comment by YeongBean** [comment]
커밋 메세지는 말 그대로 커밋할 때 남기는 메세지 입니다.
커밋은 백업시점 만들기 같은거고요.
커밋 메세지는 이 지점을 만들때 넣고 싶은 메세지(왜 이 지점을 만들었는가/수정사항 등등...)을 넣을 수 있겠네요

**Comment by Leeyoohyuk** [comment]
이해 잘됐어용~ 링크들어가서 보니 sha 7자리? 인가 적으라던 문제가 왜그런지도 덤으로 알았내요

**Comment by JINHYUNGP** [comment]
바뀐걸 임시저장 - 주석달기
