### ISSUE TITLE
Regularization이 잘 이해가 안갑니다.

### ISSUE THREAD

**Issue by JunjaK** [KHU-Dcom-Study/2018-1-DeepLearning-Study#20]
모두의 딥러닝 7-1에서 Regularization을 cost함수가 굴곡이 심하지 않게 쫙펴주는 일이라고 합니다.
여기서 기존의 cost함수에 새로운 가중치[regularization strength*tf.reduce_mean(tf.square(W))]를 더해주는 것이 왜 cost 함수의 굴곡을 줄여주는지 궁금합니다.

**Comment by kairos03** [comment]
Regularization은 Overfitting을 방지하기 위한 방법중에 하나로 그 세부 방법에따라 L1, L2 로 구분됩니다. 굴곡을 펴준다는 표현은 잘 모르겠으나, 웨이트들의 값의 표준편차가 작도록 훈련시키기 위해 보통 L2 를 사용합니다. 딥러닝에서 예전에 Regularization 을 cost 에 사용하였으나, Dropout이 나온 이후 잘 쓰지 않는 추세입니다.

**Comment by cometonf** [comment]
Regulization과 Dropout을 같이 사용하면, Dropout만 사용한 것보다 결과가 안좋은가요?

**Comment by kairos03** [comment]
사용된 모델에 따라 다른 결과가 나오나, 다수 실험에의해 검증된 여론은 같이쓰나 Dropout만 쓰나 비슷한걸로 알고 있습니다.

**Comment by JINHYUNGP** [comment]
overfitting을 줄이기 위한 수단, 융통성 있게 만듦
