### ISSUE TITLE
Deep NN의 hypothesis

### ISSUE THREAD

**Issue by YeongBean** [KHU-Dcom-Study/2018-1-DeepLearning-Study#21]
```
\\\    [1, 0, 0],  # 기타
    [0, 1, 0],  # 포유류
    [0, 0, 1],  # 조류
-----------------------------------------------------------------------------
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

# 첫번째 가중치의 차원은 [특성, 히든 레이어의 뉴런갯수] -> [2, 10] 으로 정합니다.
W1 = tf.Variable(tf.random_uniform([2, 10], -1., 1.))
# 두번째 가중치의 차원을 [첫번째 히든 레이어의 뉴런 갯수, 분류 갯수] -> [10, 3] 으로 정합니다.
W2 = tf.Variable(tf.random_uniform([10, 3], -1., 1.))

# 편향을 각각 각 레이어의 아웃풋 갯수로 설정합니다.
# b1 은 히든 레이어의 뉴런 갯수로, b2 는 최종 결과값 즉, 분류 갯수인 3으로 설정합니다.
b1 = tf.Variable(tf.zeros([10]))
b2 = tf.Variable(tf.zeros([3]))

# 신경망의 히든 레이어에 가중치 W1과 편향 b1을 적용합니다
L1 = tf.add(tf.matmul(X, W1), b1)
L1 = tf.nn.relu(L1)

# 최종적인 아웃풋을 계산합니다.
# 히든레이어에 두번째 가중치 W2와 편향 b2를 적용하여 3개의 출력값을 만들어냅니다.
model = tf.add(tf.matmul(L1, W2), b2)
```
\\\
위에서 마지막 줄의 model이 Linear Regression으로 치면 hypothesis같은 건가요?

그리고
W1은 행렬 크기가  [2,10]이고 X는 상수이니 X와 W1을 곱한 행렬의 크기는 [2,10]이고
b1은 크기가 [1,10] 이나 [10,1] 둘 중 하나일거 같은데 어느경우던 더할 수 없을거 같아요

혹시 b1,b2의 tf,zeros[10] 이 부분이 행렬의 크기가 아닌 다른 의미가 있는건가요?

**Comment by kairos03** [comment]
1. 위에서 마지막 줄의 model이 Linear Regression으로 치면 hypothesis같은 건가요?
 :arrow_right: 네, 뉴럴 각각의 hypothesis 는 wX+b죠? 이것들이 모여서 모델이라는 큰 hypothesis 가 되는겁니다.

2. W1은 행렬 크기가 [2,10]이고 X는 상수이니 X와 W1을 곱한 행렬의 크기는 [2,10]이고
b1은 크기가 [1,10] 이나 [10,1] 둘 중 하나일거 같은데 어느경우던 더할 수 없을거 같아요

혹시 b1,b2의 tf,zeros[10] 이 부분이 행렬의 크기가 아닌 다른 의미가 있는건가요?

:arrow_right: 입력값 X는 상수가 아닙니다. 
tf. placeholder() 는 아래와 같이 세개의 인자를 받을 수 있는데요, shape을 정해주지 않으면 모든 행렬의 데이터를 다 받을 수 있습니다. 
![image](https://user-images.githubusercontent.com/6357456/38093676-a360d7ce-33a6-11e8-9441-8a2005b467a6.png)

이 예제에서의 입력 데이터는 
```
# [털, 날개]
x_data = np.array(
[[0, 0], [1, 0], [1, 1], [0, 0], [0, 0], [0, 1]])
``` 
이고, shape은 (6,2) 입니다.

그럼 (6,2) * (2,10) + (10) 이 되겠죠?

**Comment by YeongBean** [comment]
그럼 (6,2) * (2,10) + (10) 에서 
(6,2) * (2,10)의 결과로 나온 행렬의 모든 원소에 10을 더해주는건가요?

**Comment by cometonf** [comment]
2. 부연 설명
그럼 L1 = (6,10) + b1 이 됩니다.
그런데 b1의 shape은 (10,)으로 (6,10)과는 다릅니다.
여기서 덧셈을 위해 자동으로 b1 shape이 변경됩니다.
b1을 6번 복사한다고 생각하면 될 것 같습니다.
그래서 (6,10)으로 변경되서 더해집니다.

**Comment by YeongBean** [comment]
오 이해 잘 됐습니다
감사합니다^^

**Comment by JINHYUNGP** [comment]
```   블라블라 ``` 회색처리
