### ISSUE TITLE
git 질문 마지막장 master/origin 의 의미

### ISSUE THREAD

**Issue by Leeyoohyuk** [KHU-Dcom-Study/2018-1-DeepLearning-Study#22]
git 질문 마지막장 master/origin 의 의미

**Comment by kairos03** [comment]
1. master는 보통 해당 repository를 대표하는 branch로 git init시에 자동으로 생성 되는 첫 브렌치입니다. 
2. origin은 보통 메인 remote reposiroty을 의미합니다.
3. master/origin은 origin이라는 이름의 remote repository에 있는 master brach라는 뜻입니다.

**Comment by Leeyoohyuk** [comment]
그렇다는건 origin은 그냥 이름일뿐 속성이 없는건가요? 변경도 가능?

**Comment by kairos03** [comment]
넹 변경 가능합니다. 다만 push, pull, fetch 할 때 origin 은 생략이 가능합니다.
```bash
git push        # same
git push origin # same 
```
