### ISSUE TITLE
git add의 의미

### ISSUE THREAD

**Issue by JINHYUNGP** [KHU-Dcom-Study/2018-1-DeepLearning-Study#23]
git add를 하면 수정한 내용이 저장되는건가요? 제가 똑바로 이해한건가요?? ㅜ

**Comment by Leeyoohyuk** [comment]
repository에 새로운 git을 생성하는거에용 수정과 저장의 의미와는달라용

**Comment by JINHYUNGP** [comment]
git add - tracked  : stage에 올라감
