### ISSUE TITLE
진배형이 올린코드 돌렸는데 

### ISSUE THREAD

**Issue by JINHYUNGP** [KHU-Dcom-Study/2018-1-DeepLearning-Study#27]
![1](https://user-images.githubusercontent.com/37439745/38142728-7509caac-3478-11e8-8f8b-32e8473202b5.PNG)
이렇게 나옵니다.. 코드 자체는 돌아가는데 뭐가 문제였던걸까요? 첫줄 가보면 주석만 달려있습니당

**Comment by JunjaK** [comment]
이거는 터미널에 asdf&를 입력해서 나오는 문제 같네요.
![image](https://user-images.githubusercontent.com/30404630/38145799-121e4946-3486-11e8-85e9-825d0b72d91c.png)
터미널에 asdf& 입력하면 저렇게 출력됩니다.
