### ISSUE TITLE
MNIST DNN 코드 14줄 keep_prob 의 의미

### ISSUE THREAD

**Issue by 1core2life** [KHU-Dcom-Study/2018-1-DeepLearning-Study#29]
keep_prob 의 정확한 의미는 무엇인가요?

**Comment by kairos03** [comment]
dropout parameter로 몇 퍼센트의 확률로 해당 노드의 연결을 끊을지 지정하는 인자 입니다. 
0.9는 90%의 확률로 해당 노드의 연결을 유지 하겠다는 뜻입니다.
