### ISSUE TITLE
모두의 딥러닝 5장공부중인데 decode_csv의 정확한 용도를 모르겠습니다.

### ISSUE THREAD

**Issue by Leeyoohyuk** [KHU-Dcom-Study/2018-1-DeepLearning-Study#34]
그냥 대량의 데이터가 있을 경우 쓴다는 것은 알겠는데
정확한 원리가뭐죠 ? 그리고 대량인지 아닌지로만 사용 유무를 판단하는건가요?

**Comment by 1core2life** [comment]
+ 추가로 답변!
csv 확장자는 데이터를 , 로 구분한 텍스트 파일입니다. decode_csv는 csv 파일을 파싱하는 함수입니다

**Comment by Leeyoohyuk** [comment]
데이터를 ,로 구분하는 것은 이해가 갔으나
kaggle에서 실제 예제 데이터를 받아서 로드해보려고 하니 불러올 범위를 얼마나 지정해주어야 할지 모르겠습니다. ([:, :-1] 이런거 )
실제 엑셀상에서는 데이터에 이름 및 여러 요소들이 포함되어있고
x,y단 두가지로 단순화 할 수 있는 형식이 아니던데 좋은 방법 없을까요?

**Comment by Leeyoohyuk** [comment]
그리고 이미지 첨부는 앞으로 그렇게하도록 할게요~
