### ISSUE TITLE
feed_dict를 쓰는 이유?

### ISSUE THREAD

**Issue by YeongBean** [KHU-Dcom-Study/2018-1-DeepLearning-Study#36]
feed_dict=(X: .... )라는 구문은 학습이 끝난 이후 사용자가 임의의 값을 물어보는건가요?

**Comment by Leeyoohyuk** [comment]
제가 공부한 바로는 학습이 끝난 이후 feed_dict를 사용하는 것은 이해하시고 계시는게 맞습니다.
즉, 학습 이후에 x데이터에 대해 결과가 어떻게 나올지 예측하고싶을때 feed_dict를 사용하는걸로 알고있습니다.

**Comment by YeongBean** [comment]
확인 감사합니다
