### ISSUE TITLE
모두의 딥러닝 conv 에서 질문

### ISSUE THREAD

**Issue by JINHYUNGP** [KHU-Dcom-Study/2018-1-DeepLearning-Study#38]
## Issue Summary
[//]: # (이슈 요약)
5*5 뒤에 *3은 무엇을 의미하나용>
## Detail
[//]: # (상세내용)

## Reference 
[//]: # (참고 사진, 사이트 링크)

![default](https://user-images.githubusercontent.com/37439745/38718705-55588e4e-3f29-11e8-9610-8d074ea837f6.PNG)

[//]: # (질문시 Assignee는 `자기자신`, Label은 `Question`, milestone은 `N차  #스터디`로 해주세요.)

**Comment by kairos03** [comment]
이미지의 Depth, 여기서는 색 채널로 RGB라 3입니다.

**Comment by JINHYUNGP** [comment]
모든 이미지에 depth가 있나요? 가령 흑백사진이면 2 인가요??

**Comment by kairos03** [comment]
모든 사진에는 Depth가 있습니다.
흑백은 검은색의 정도에 따른 이미지 임으로 1
보통 이미지는 3
감마 값이 추가된 이미지는 4 입니다.

**Comment by JINHYUNGP** [comment]
relu 와 컨볼루션 레이어를 거치면 나오는 이미지를 가지고 학습했다고 하는건가요??

**Comment by kairos03** [comment]
질문이 이해가 안되네요 relu와 convolution을 거치면 나오는 이미지가 학습된 최종 결과 값이냐는 질문인가요?
