### ISSUE TITLE
Git 이해하기

### ISSUE THREAD

**Issue by kairos03** [KHU-Dcom-Study/2018-1-DeepLearning-Study#4]
https://www.codecademy.com/learn/learn-git
git 학습해오기

100% 완료 캡쳐 해오기

**Comment by JunjaK** [comment]
![default](https://user-images.githubusercontent.com/30404630/37817016-8b03c60c-2eb8-11e8-8a7a-3a2aa48e24b5.jpg)

**Comment by 1core2life** [comment]
![image](https://user-images.githubusercontent.com/21700627/37817207-61e22e8e-2eb9-11e8-8a62-5ddcdf93d71a.png)

**Comment by YeongBean** [comment]
![default](https://user-images.githubusercontent.com/37439238/37865215-9a968e60-2fbc-11e8-9177-cd8fbf8d3f7d.png)

**Comment by YeongBean** [comment]
![default](https://user-images.githubusercontent.com/37439238/37865226-cc13789a-2fbc-11e8-9f5a-de9e767cfa38.png)

**Comment by Leeyoohyuk** [comment]
![image](https://user-images.githubusercontent.com/37439276/38093560-4f0b58e8-33a6-11e8-8dc1-6d71f0382174.png)
