### ISSUE TITLE
이미지를 학습시키기 위해 파일을 변환해야 하나요?

### ISSUE THREAD

**Issue by YeongBean** [KHU-Dcom-Study/2018-1-DeepLearning-Study#42]
## Detail
[//]: # (상세내용)
CNN을 이용해 학습시키려면 학습시킬 이미지들이 필요할텐데요,
어떻게 하면 학습시킬 이미지를 불러올 수 있는지를 찾다가 아래와 같은 주소에서 변환하라는 이야기를 합니다.

강아지 12500장, 고양이12500이 담긴 train압축파일 안의 이미지를 모두 변환해야 학습시킬 수 있나요?

## Reference 
[//]: # (참고 사진, 사이트 링크)
http://gusrb.tistory.com/12

[//]: # (질문시 Assignee는 `자기자신`, Label은 `Question`, milestone은 `N차 스터디`로 해주세요.)

**Comment by YeongBean** [comment]
고렇군요 빠른 답변 감사합니다

**Comment by kairos03** [comment]
https://github.com/jiqixueyuan/cats-vs-dogs
