### ISSUE TITLE
모델의 train accuracy가 줄어들수도 있나요

### ISSUE THREAD

**Issue by YeongBean** [KHU-Dcom-Study/2018-1-DeepLearning-Study#43]
## Detail
[//]: # (상세내용)
![default](https://user-images.githubusercontent.com/37439238/39881721-ae303438-54bc-11e8-9b89-76cd5f63aa0d.jpg)

MNIST에서는 train accuracy가 학습이 진행될때마다 계속 증가하는 추세였는데요,
cat vs dog같이 같은 답(라벨)을 가진 이미지끼리도 서로 상이한 모습을 가지고 있다면 train accuracy가 반드시 증기하지는 않는건가요?
(강아지도 까만색 흰색 주황색, 삽살개 포메라니안 도베르만 같이 여러 종류가 있는것 처럼)

## Reference 
[//]: # (참고 사진, 사이트 링크)

[//]: # (질문시 Assignee는 `자기자신`, Label은 `Question`, milestone은 `N차 스터디`로 해주세요.)

**Comment by kairos03** [comment]
모델에서 loss를 줄여나가다가 로컬 옵티마에 진입 후 탈출 글로벌 옵티마로 찾아가는 과정입니다. 
Under fitting이 일어나는 경우 Learning Rate나 다른 Hyperparameter를 조정하보고 너무 fitting이 안되면 모델이 입출력을 표현하기에 부족하다는 것입으로 모델을 조금더 복잡하게 설계할 필요가 있습니다.
