### ISSUE TITLE
train 도중 같은 정확도가 빈번하게 나옵니다.

### ISSUE THREAD

**Issue by JunjaK** [KHU-Dcom-Study/2018-1-DeepLearning-Study#44]
![image](https://user-images.githubusercontent.com/30404630/39883315-74fb605c-54c1-11e8-9234-77fdc3d68aa5.png)
![image](https://user-images.githubusercontent.com/30404630/39883462-e9e3c3dc-54c1-11e8-9433-a6f178354ea7.png)

train 결과를 프린트 하는 도중, 사진에 보이듯 75%, 65.62% 등등 특정한 정확도가 빈번하게 나옵니다.

분명히 이미지 배치에서 셔플 돌렸는데 왜 이런식으로 특정한 정확도가 자주 나오는지 궁금합니다.

**Comment by kairos03** [comment]
학습 중에는 accuracy보다는 loss를 보는 것이 중요합니다. 
같은 정확도가 빈번하게 나오는 것은 특정 이미지는 학습이 되고 특정 이미지는 학습이 안되고 있다는 것을 의미할 수 있습니다. 이런 경우 학습이 안되는 이미지가 무엇인지 찾아보고 해당 이미지를 학습하기 위해 새로운 모델을 구성하거나 preprocessing 등의 방법을 고민해 보아야 합니다. 
혹은, 코드상의 문제일 가능성도 있습니다.
