### ISSUE TITLE
학습을 계속해도 학습률이 오르지 않는 경우

### ISSUE THREAD

**Issue by YeongBean** [KHU-Dcom-Study/2018-1-DeepLearning-Study#45]
## Detail
[//]: # (상세내용)
![cat dog training](https://user-images.githubusercontent.com/37439238/39968203-69b0aed8-5704-11e8-95c4-7f7aacba3d18.png)

모델을 바꾸어 돌려본 결과 80~90%대에 train accuracy가 왔다갔다 하는데 1300회 가량의 결과가 비슷하다면 모델을 좀 더 복잡하게 바꾸어야 하는걸까요

<<지난 발표자중 한분이 '나는 좀 더 간단한 모델로 더 많이 학습시켜서 정확도를 높이겠다' 라고 한것이 생각나서 하는 질문입니다. >>

## Reference 
[//]: # (참고 사진, 사이트 링크)

[//]: # (질문시 Assignee는 `자기자신`, Label은 `Question`, milestone은 `N차 스터디`로 해주세요.)

**Comment by cometonf** [comment]
learning rate가 너무 높은 것은 아닐까요?

**Comment by YeongBean** [comment]
낮춰서 해보도록 하죠

**Comment by kairos03** [comment]
learning rate, epoch 등 hyper parameter를 바꿔보고, 그래도 안되면 모델을 더 복잡하게 해보세요.

**Comment by YeongBean** [comment]
learning rate를 줄이고 컨볼루션 레이어를 하나 더하니까 나아졌네요
