### ISSUE TITLE
트레이닝 오류

### ISSUE THREAD

**Issue by Youmin-Kim** [KHU-Dcom-Study/2018-1-DeepLearning-Study#48]
## Detail
[//]: # (상세내용)
개고양이 training 도중에 이미지 로드는 완료했지만 컴퓨터 사양이 안되서 안돌아가는건지 확실치 않아 여기에 올려봅니다....
## Reference 
[//]: # (참고 사진, 사이트 링크)
![training](https://user-images.githubusercontent.com/27268083/40111731-b7b185ee-593e-11e8-8ad4-06ae5e2af488.PNG)

[//]: # (질문시 Assignee는 `자기자신`, Label은 `Question`, milestone은 `N차 스터디`로 해주세요.)

**Comment by kairos03** [comment]
메모리 문제 같은데 배치 사이즈를 줄이는게 해답이 될 것 같습니다.
