### ISSUE TITLE
github와 git의 차이가 뭔가요?

### ISSUE THREAD

**Issue by kairos03** [KHU-Dcom-Study/2018-1-DeepLearning-Study#7]
github와 git의 차이점이랑 
쓰임새좀 알려주세요

**Comment by Leeyoohyuk** [comment]
깃허브는 분산 버전 관리 툴인 깃(Git)을 사용하는 프로젝트를 지원하는 웹호스팅 서비스입니다. GitHub는 영리적인 서비스와 오픈소스를 위한 무상 서비스를 모두 제공합니다. 가장 인기있는 Git 호스팅 사이트이자 2011년의 조사에서는 가장 인기있는 오픈 소스 코드 저장소입니다. 

깃(Git 은 프로그램 등의 소스 코드 관리를 위한 분산 버전 관리 시스템입니다. 서버에 의존하지 않고 전체 기록의 추적과 관리가 가능하다는 특징이 있습니다.

**Comment by kairos03** [comment]
[3rd. Git and Github.pdf](https://github.com/KHU-Dcom-Study/2018-1-DeepLearning-Study/files/1840538/3rd.Git.and.Github.pdf)
